channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::numpy=1.26.0
  - conda-forge::matplotlib=3.8.1
  - conda-forge::pandas=2.1.2
  - conda-forge::tqdm=4.66.1
  - conda-forge::ipykernel=6.26.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::pytorch-lightning=2.1.0
  - conda-forge::tensorboard=2.15.1
  - conda-forge::torchmetrics=1.2.0
  - pytorch::pytorch=2.1.0
  - pytorch::pytorch-cuda=11.8